【C6.2】タスクの新規作成ページを作り、機能を実装する（ＭＶＣ）２
＜まだcreateボタンアクションも実装前だが、
　先にnewページのエラーと格闘＆無理なら次イク！＞

（※え～と、出てたエラーは【NoMethodError】だったわね。
　　詳細は『undefined method ‘tasks_path’』ってヤツで、
　　タスクnewビュー７行目の
　　＜％= form_with（model: @task, local: true） do |f| ％＞がアカンって。）

（※もう良く分からんから答えを見ると、
＜％= form_with（model: @task, local: true） do |f| ％＞を
＜％= form_with（model: @task, url: user_tasks_path（@user）,local: true） do |f| ％＞
ってな感じに
「url: user_tasks_path（@user）」を入れなアカンみたい。
今までのテキストにはそんなん出てこなかったのに何故？とりまヤってみる。）

１：（app/views/tasks/new.html.erb）内の

・７行目
＜％= form_with（model: @task, local: true） do |f| ％＞を
＜％= form_with（model: @task, url: user_tasks_path（@user）,local: true） do |f| ％＞
に変更（答え【エラー解決ドリル】の丸写し）。

（※うぉい！またエラー違うエラー出たヤンケ！
　　今度のエラーは【ActionController::UrlGenerationError】。
　　場所は今つまづいてる７行目。
　　詳細は
　　『No route matches {:action=＞”index”, :controller=＞”tasks”, :user_id=＞nil}』
　　だってさ。
　　要は、
　　『indexアクションでtasksコントローラーが定義されとるけど、user_idが空白やぞ～。』
　　だと思う。

　　・・・なんでindexアクションの話？俺が格闘中なのはnewアクションだぞ？

　　ワケ分かんないけど、『user_idが nilよぉ＝定義されとらんよぉ』ってんなら、
　　newアクションにも「@user = User.find（params[:user_id]）」を入れてみっか。）

２：（controllers/tasks_controller.rb）内の
・９行目に「@user = User.find（params[:user_id]）」を新記述。

（※なんと！エラー解消！ヤッた！！
　　・・・でも何故？なんでエラー場所がnewアクションなのに、
　　indexアクション内のuser_idが空白だよなんてエラーが出たわけ？

　　おっとここでミーティング時刻だ。時間あれば聞いてみっかな。）

＜※【B8】以降でヤる予定リスト※＞
・予定１：【views/users/_form.html.erb】作成＆余計なテキスト削除・・・未！
・予定２：エラーメッセージを見本通りに合わせる＆重複文削除・・・未！
・予定３：params.require使って、task_paramsを定義・・・未！
・予定４：「'＃'」のままのパス系を今度ちゃんと書く・・・未！

（以上な現状！）