【C6.1】タスクの新規作成ページを作り、機能を実装する（ＭＶＣ）１
（※newアクションとcreateアクションとnew.html.erbビューが
　　必要そうってのは分かるが・・・
　　とりま【勤怠チュート5.5】ユーザー登録をマネつつ、
　　あと【Railsアプリ3.7】新規投稿ページも参考にしよう。）

（※つか、気になるのが・・・
　　【勤怠チュート】でも【Railsアプリ】でも、
　　どちらも新規登録や新規投稿のnew＆createを作るまえに、
　　showアクション＆showビュー、つまり【C8】にあたりそうな
　　詳細ページを若干、先に作ってんのよね・・・。
　　ど～なんだろ？・・・まぁ気にせず、新規作成を進めてみっか。）

（※順番的には、
　　・まずnewアクション設定、
　　・次にnew.html.erbの作成、
　　・最後にcreateアクションで新規作成ボタンを機能設定。
　　って感じの流れになるっぽいな。）

１：（controllers/tasks_controller.rb）内の

・７行目に空白行を追加。
・８行目に「def new」を新記述。
・９行目に「end」を新記述して〆。

（※とりまnewアクション設置。
　　次はnew.html,erbを生成だな。アレだろ、touch～でview生成だろ。）

２：ターミナルで「touch app/views/tasks/new.html.erb」を実行。

（※良し。お次は・・・
　　まぁ当然、この出来立て真っ白newビューに色々と新記述よね。
　　ここは見本のタスク新規作成ページを検証モードで見ていこう。
　　前回【C5】で作ったタスクindexビューや、
　　元々存在するユーザーnewビューも参考にしよう。）

（※あ、あとprovideの第２引数か・・・もう答え見ちゃお。
　　・・・'New Task'で良いみたい。
　　正直・・・indexビューの時が「@user.name」で
　　今回のnewビューの時が「'New Task」になる意味が分からん。
　　・・・slack検索してもググっても良く分からんかったし。
　　・・・次回のチームＭＴＧん時に聞いてみるかな。）

３：出来立て（app/views/tasks/new.html.erb）内の

・１行目に＜％ provide（:title, 'New Task'）％＞を新記述。
・２行目に空白行を追加（他ビューを参考）。
・３行目に＜h1＞タスク新規作成＜/h1＞を新記述（見マネ）。
・４行目に空白行を追加（他ビューを参考）。
・５行目に＜div class=”row”＞を新記述（見マネ）。
・６行目に＜div class=”col-md-8 col-md-offset-2”＞を新記述（見マネ）。

・７行目に・・・ちょっと待て。なんじゃこりゃ？
　　　　　見マネの該当タグには
　　　　　「form action=”/users/ユーザーid/tasks”」とか
　　　　　「method= ”post”」とか書いてある・・・
　　　　　・・・あぁ～これアレだ！【form_withヘルパーメソッド】ってヤツだ！
　　　　　出た・・・苦手なヤツや・・・でも、避けては通れんな。
　　　　　これはアレだな。
　　　　　一旦、ユーザーnewビューを参考にしよう。
　　　　　ちょうど【勤怠チュート5.5】のド頭もそのくだりだし。
　　　　　・・・っと、その前に一旦、div達を〆めとこう。

・８行目に＜/div＞を新記述して〆。
・９行目に＜/div＞を新記述して〆。

＜＜以下、form_with ヘルパーメソッドと悪戦苦闘の復習＞＞

（※とりま、ユーザーnewビューのform_withヘルパーメソッド記述は

　　 ＜％= form_with（model: @user, local: true） do |f| ％＞

　　ってなってんのよね。
　　model:の引数はたぶん@taskにするとして。
　　第２引数の「local: true」って・・・何コレ？
　　どのテキストにも説明が無い。とりま付けとくか。

　　だからform_with ヘルパーメソッドの始まりは
　　＜％= form_with（model: @task, local: true） do |f| ％＞

　　とでも書いとくかな。）

（※あとはその後の名称＆詳細＆新規登録ボタンよね。
　　【勤怠チュート5.5.1】のform_withヘルパーメソッド説明を見るに・・・

　　・htmlで＜label class～＞と記載の項目名は＜％= f.label～＞。
　　・htmlで＜input class～＞と記載の入力部分は＜％=ｆ,項目タイプ_field～＞かな。

　　・html＜input type～＞はボタン部分ね。＜％= f.submit～＞っぽいな。）

（※だから
    タスク名称の項目名htmlは
＜label class=”label-form” for=”task_name”＞名称＜/label＞だから
＜％= f.label :name, class: ”label-form”％＞で良さげ。

　　タスク名称の入力部分htmlは　　
＜input class=”form-control” type=”text” name=”task[name]”＞だから
＜％= f.text_field :name, class: ”form-control”％＞で良さげ。

　　タスク詳細の項目名htmlは
＜label class=”label-form” for=”task_description”＞詳細＜/label＞だから
＜％= f.label :description, class: ”label-form”％＞で良いんじゃないかな。

　　・・・え？ナニコレ？？
　　タスク詳細の入力部分のhtml・・・
＜textarea rows=”5” class=”form-control” name=”task[description]”＞＜/textarea＞て？
＜％= f.text_field :description, class: ”form-control”％＞じゃ・・・たぶんダメだろ。
　　「rows=”5”」は５行って意味だろけど、どこに書けば良いわけ？
　　そもそも「textarea」って言われてもさぁ・・・。
　　・・・もう、答え見るわ・・・ワケ分からんもん。

　　タスク詳細の入力部分のhtmlの答えを見た結果・・・
＜textarea rows=”5” class=”form-control” name=”task[description]”＞＜/textarea＞は
＜％= f.text_area :description, rows: 5, class: ”form-control”％＞って書くみたい。
　　・・・もう、『こ～ゆ～書き方なんだな』としか言いようがないわよ。
　　
　　htmlが＜input＞で「type=”text”」だとＥＲＢは＜％= f.text_field＞で・・・
　　htmlが＜textarea＞だとＥＲＢは＜％= f.text_area＞・・・ってワケ？知らね～し！
　　とりま、行数の指定【rows: 数字】はclass属性の既述前に書くべしなんだろなぁ。

　　まぁ、理解したって事にして次、ボタンや！

　　タスク新規登録ボタンhtmlは
＜input type=”submit” name=”commit” value=”新規登録” class=”btn btn-lg btn-primary btn-form” data-disable-with=”新規登録”＞
　　と書いてあるが、これは
＜％= f.submit 新規登録, class: ”btn btn-lg btn-primary btn-block btn-form”％＞で良さげや。
　　htmlケツの『data-disable-with=”新規登録”』って部分はテキストにもそうなってたから、
　　たぶんhtml化した際に、自動でケツに付くんでしょうよ。

　　こんな感じかなぁ。
　　あ、表示系ＥＲＢとはいえ、
　　form_withヘルパーメソッド全体は＜％ end ％＞で〆なアカンぽいから、
　　最後は＜％ end ％＞を忘れずに！やな！！）

＜＜以上、復習＆答え見ての初理解を含め、自力form_withヘルパーメソッドの初記述に戻る。＞＞

４：（app/views/tasks/new.html.erb）内の

・７行目に
＜％= form_with（model: @task, local: true） do |f| ％＞を新記述（たぶん）。
・８行目に空白行を追加。

・９行目に
＜％= f.label :name, class: ”label-form”％＞を新記述（見マネ）。
・１０行目に
＜％= f.text_field :name, class: ”form-control”％＞を新記述（見マネ）。
・１１行目に空白行を追加。

・１２行目に
＜％= f.label :description, class: ”label-form”％＞を新記述（見マネ）。
・１３行目に
＜％= f.text_area :description, rows: 5, class: ”form-control”％＞を新記述（答マネ）。
・１４行目に空白行を追加。

・１５行目に
＜％= f.submit 新規登録, class: ”btn btn-lg btn-primary btn-block btn-form”％＞を新記述（見マネ）。
・１６行目に
＜％ end ％＞を新記述してform_withヘルパーメソッド内を〆。

（※んで、ちょっとテキストを遡ったんだけど、
　　コントローラーに戻ってnewアクション内に「@user = User.new」って定義しとるね。
　　『＃ ユーザーオブジェクトを生成し、インスタンス変数に代入します。』だって。

　　じゃあコッチは「@task = Task.new」って定義して、
　　『＃ タスクオブジェクトを生成し、インスタンス変数に代入します。』って感じだろね。）

５：（controllers/tasks_controller.rb）内の
・９行目に「@task = Task.new」を新記述。

（※さ、こんな感じかな。
　　サーバー起動して、urlに「users/1/tasks/new」と打って閲覧してみるか。）

（※はい、当たり前のようにエラーが出たよｗｗ
　　うわ～【NoMethodError】だ。
　　詳細は『undefined method ‘tasks_path’』ってヤツで、
　　タスクnewビュー７行目の
　　＜％= form_with（model: @task, local: true） do |f| ％＞がアカンって。）
　　
　　・・・一旦、区切るわ。
　　次回【C6.2】、エラーと格闘＆無理なら次イク！）

＜※【B8】以降でヤる予定リスト※＞
・予定１：【views/users/_form.html.erb】作成＆余計なテキスト削除・・・未！
・予定２：エラーメッセージを見本通りに合わせる＆重複文削除・・・未！
・予定３：params.require使って、task_paramsを定義・・・未！
・予定４：「'＃'」のままのパス系を今度ちゃんと書く・・・未！

（以上な現状！）